---
boxes:
  -
    box_name: trusty64
    box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
    hostname: trusty64
    networks:
      - name: private_network
        ip: 10.99.250.10
    spec:
      cpus: 1
      memory: 2048
      biosbootmenu: disabled
    bootstrap:
      type: script
      script: ./scripts/bootstrap.sh
    